### ISSUE TITLE
Mudar a estrutura do projeto

### ISSUE THREAD

**Issue by Sevlak** [dami-pie/napi#1]
Decidimos que a estrutura/arquitetura do projeto seguirá o modelo MVC. Devemos mudar a estrutura e atualizar o `go.mod` para que ele aponte para o novo repositório.

**Comment by Sevlak** [comment]
Conforme acordado no Discord, as outras mudanças na estrutura que serão implementadas são:

- [ ] Mudar o comportamento do carregamento de variáveis de ambiente (de `init()` para uma chamada de função)
- [ ] O arquivo `routes.go` será unido ao arquivo `router.go`.
- [ ] As rotas da API ficarão na pasta `/routes`, contendo um array com as rotas
- [ ] Criação das pastas: `/sql` (contém o .sql de inicialização/população) e `src/migrations`
- [ ] Renomeação de pasta: `src/auth` vira `src/services`.

**Comment by erick-andrade1** [comment]
Foi necessário fazer pequenas mudanças no arquivo `Router.go` por conta do formato que o Go lida com imports de arquivos

**Comment by Sevlak** [comment]
Fechado com o PR #21.
