### ISSUE TITLE
Instanciamento e utilização de migrations

### ISSUE THREAD

**Issue by Sevlak** [dami-pie/napi#18]
A partir de agora, iremos utilizar a ferramenta [Goose](https://github.com/pressly/goose) para a administração de entidades já conhecidas e pré-definidas no projeto.

- [x] Instalação do Goose
- [x] Criação da pasta de migrations dentro de `src`
- [x] Criação das primeiras migrations utilizando os .sql fornecido

**Comment by erick-andrade1** [comment]
Pode ajudar a entender como utilizar o goose: `https://citizix.com/managing-database-migrations-with-golang-goose-using-incremental-sql-changes/`
